version: "2"

services:
  wordpress:
    image: wordpress:php7.1
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: super-secure-password
    volumes:
      - .:/var/www/html/wp-content/themes/hmww
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: super-secure-password
